rmdir /S /Q "D:\\Games\\Foundry\\dev_data_088\\Data\\modules\\journal-scaler"
mkdir "D:\\Games\\Foundry\\dev_data_088\\Data\\modules\\journal-scaler"
Xcopy /E /I /Y /Q scripts "D:\\Games\\Foundry\\dev_data_088\\Data\\modules\\journal-scaler\\scripts"
Xcopy /E /I /Y /Q languages "D:\\Games\\Foundry\\dev_data_088\\Data\\modules\\journal-scaler\\languages"
Xcopy /E /I /Y /Q styles "D:\\Games\\Foundry\\dev_data_088\\Data\\modules\\journal-scaler\\styles"
Xcopy /Y /Q module.json "D:\\Games\\Foundry\\dev_data_088\\Data\\modules\\journal-scaler"
